<a href="https://colab.research.google.com/github/fabioeduardo25/Data-Science-using-Python/blob/main/DS_Python_Matrizes_Fabio_Eduardo_BI23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
#Lista de Exercicios
#
#1.Você tem uma lista de número: [6,7,4,7,8,4,2,5,7,'hum','dois']. 
#A ideia do exercício é tirar a média de todos os valores contidos na lista, 
# porém para fazer o cálculo precisa remover as strings.

lista_de_numeros=[6,7,4,7,8,4,2,5,7,'hum','dois']
lista_de_numeros.remove('hum')
lista_de_numeros.remove('dois')
cont=0
soma=0
for valor in lista_de_numeros:
    cont+=1
    if isinstance(valor, (int,float)):
        soma+=valor
media=soma/cont
print(soma)
print(cont)
print(media)

50
9
5.555555555555555


In [19]:
#2.Crie um método que receba duas matrizes, some os valores total de cada matriz
# e depois multiple o resultado delas e retorne o valor.

def calcule_matriz(matriz1,matriz2):
    soma1=0
    soma2=0
    for x in matriz1:
        soma1+=x
    for x in matriz2:
        soma2+=x
    valor=soma1*soma2
    print('A soma da matriz 1 é = ' + str(soma1))
    print('A soma da matriz 2 é = ' + str(soma2))
    print('A multiplicação é = ' + str(valor))
    return valor

teste=calcule_matriz([1,3,5,6], [3,4,5,2])
print(teste)

A soma da matriz 1 é = 15
A soma da matriz 2 é = 14
A multiplicação é = 210
210


In [23]:
#3.Criar uma matriz nxm (n = 5, m =7)
#a.faça a matriz transposta desta matriz
#b.somar toda matrix
#c.somar todas as colunas
#d.somar todas as linhas.
#e.retorne o maior valor
#f.retorne o menor valor.

import numpy as np
from numpy import random

#Criar uma matriz nxm (n = 5, m =7)
n = 5
m = 7
matriz1 = np.random.randint(1,99, (n,m))
print('Matriz')
print(matriz1)
#faça a matriz transposta desta matriz
matriz2=matriz1.T
print('Matriz Transposta')
print(matriz2)
#somar toda matrix
print('Soma de toda Matriz')
print(matriz2.sum())
#somar todas as colunas
print('Soma de todas as Colunas')
print(matriz2.sum(axis=0))
#somar todas as linhas.
print('Soma de todas as Linhas')
print(matriz2.sum(axis=1))
#retorne o maior valor
print('Retorno do maior valor da Matriz')
print(matriz2.max())
#retorne o menor valor.
print('Retorno do menor valor da Matriz')
print(matriz2.min())



Matriz
[[61 85 18 72  5 30 73]
 [39 39 33 32 58 35  7]
 [75 19 28 40 95  8 27]
 [36 35 40 49 40 88 48]
 [40 58 18 55 23 10 96]]
Matriz Transposta
[[61 39 75 36 40]
 [85 39 19 35 58]
 [18 33 28 40 18]
 [72 32 40 49 55]
 [ 5 58 95 40 23]
 [30 35  8 88 10]
 [73  7 27 48 96]]
Soma de toda Matriz
1515
Soma de todas as Colunas
[344 243 292 336 300]
Soma de todas as Linhas
[251 236 137 248 221 171 251]
Retorno do maior valor da Matriz
96
Retorno do menor valor da Matriz
5


In [16]:
#4.Crie uma matriz nxn (n=5). Agora some essa matriz com a matriz do exercício 3.
n=5
matriz3 = np.random.randint(1,99, (n,n))
print(matriz2.sum()+matriz3.sum())

2837


In [20]:
#5.Crie um array de números que vai de 0 a 1000.
n=5
matriz4 = np.random.randint(1,1000, (n,n))
print(matriz4)

[[702 637 535 261 417]
 [932 634 323 224 716]
 [285 150 328 961 534]
 [668 776 156 119 363]
 [577 534 990 185 400]]


In [30]:
#6.Crie uma matriz só de zeros.
matriz5=np.zeros(5)
#ou
matriz6=[0] * 5
print(matriz5)
print(matriz6)

[0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0]
